/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './tfi-question.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../src/app/tfi/tfi-question/tfi-question.component';
const styles_TfiQuestionComponent:any[] = [i0.styles];
export const RenderType_TfiQuestionComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_TfiQuestionComponent,data:{}});
export function View_TfiQuestionComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  tfi-question works!\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n']))],(null as any),(null as any));
}
export function View_TfiQuestionComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-tfi-question',
      ([] as any[]),(null as any),(null as any),(null as any),View_TfiQuestionComponent_0,
      RenderType_TfiQuestionComponent)),i1.ɵdid(1,114688,(null as any),0,i2.TfiQuestionComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TfiQuestionComponentNgFactory:i1.ComponentFactory<i2.TfiQuestionComponent> = i1.ɵccf('app-tfi-question',
    i2.TfiQuestionComponent,View_TfiQuestionComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90ZmkvdGZpLXF1ZXN0aW9uL3RmaS1xdWVzdGlvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL3RmaS90ZmktcXVlc3Rpb24vdGZpLXF1ZXN0aW9uLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90ZmkvdGZpLXF1ZXN0aW9uL3RmaS1xdWVzdGlvbi5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90ZmkvdGZpLXF1ZXN0aW9uL3RmaS1xdWVzdGlvbi5jb21wb25lbnQudHMuVGZpUXVlc3Rpb25Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgdGZpLXF1ZXN0aW9uIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC10ZmktcXVlc3Rpb24+PC9hcHAtdGZpLXF1ZXN0aW9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsa0RBRUM7TUFBQTs7O29CQ0ZKO01BQUE7cUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
