/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/tfi/tfi-question/tfi-question.component';
import * as i1 from './tfi-question.component.ngfactory';
export function TfiQuestionComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.TfiQuestionComponent,diDeps:([] as any[]),
      lifecycleHooks:[0]},isComponent:true,selector:'app-tfi-question',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i1.View_TfiQuestionComponent_0,rendererType:i1.RenderType_TfiQuestionComponent,
      componentFactory:i1.TfiQuestionComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90ZmkvdGZpLXF1ZXN0aW9uL3RmaS1xdWVzdGlvbi5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL3RmaS90ZmktcXVlc3Rpb24vdGZpLXF1ZXN0aW9uLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
