/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './thank-you.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../logo/logo.component.ngfactory';
import * as i3 from '../../../../src/app/logo/logo.component';
import * as i4 from '@angular/router';
import * as i5 from '../../../../src/app/thank-you/thank-you.component';
const styles_ThankYouComponent:any[] = [i0.styles];
export const RenderType_ThankYouComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ThankYouComponent,data:{}});
export function View_ThankYouComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),16,'html',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['\n'])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),1,'head',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),
      (_l()(),i1.ɵeld(6,0,(null as any),(null as any),1,'logo',([] as any[]),(null as any),
          (null as any),(null as any),i2.View_LogoComponent_0,i2.RenderType_LogoComponent)),
      i1.ɵdid(7,49152,(null as any),0,i3.LogoComponent,[i4.Router],(null as any),(null as any)),
      (_l()(),i1.ɵted(-1,(null as any),['\n\n  '])),(_l()(),i1.ɵeld(9,0,(null as any),
          (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(10,(null as any),[' ',' '])),
      (_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(12,0,(null as any),
          (null as any),1,'button',[['class','button-video'],['type','button']],(null as any),
          [[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i5.ThankYouComponent = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.OnClickVideoLink()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['Informative Video'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(15,0,(null as any),
          (null as any),1,'button',[['class','button-information'],['type','button']],
          (null as any),[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i5.ThankYouComponent = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.OnClickInfoLink()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['Other Information'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n\n'])),(_l()(),i1.ɵted(-1,(null as any),
          ['\n']))],(null as any),(_ck,_v) => {
    var _co:i5.ThankYouComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,10,0,currVal_0);
  });
}
export function View_ThankYouComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'thank-you',
      ([] as any[]),(null as any),(null as any),(null as any),View_ThankYouComponent_0,
      RenderType_ThankYouComponent)),i1.ɵdid(1,114688,(null as any),0,i5.ThankYouComponent,
      [i4.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ThankYouComponentNgFactory:i1.ComponentFactory<i5.ThankYouComponent> = i1.ɵccf('thank-you',
    i5.ThankYouComponent,View_ThankYouComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90aGFuay15b3UvdGhhbmsteW91LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvdGhhbmsteW91L3RoYW5rLXlvdS5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvdGhhbmsteW91L3RoYW5rLXlvdS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90aGFuay15b3UvdGhhbmsteW91LmNvbXBvbmVudC50cy5UaGFua1lvdUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjwhRE9DVFlQRSBodG1sPlxuPGh0bWw+XG48aGVhZD5cbjwvaGVhZD5cbiAgPGxvZ28+PC9sb2dvPlxuXG4gIDxoMj4ge3t0aXRsZX19IDwvaDI+XG4gIDxidXR0b24gKGNsaWNrKT1cIk9uQ2xpY2tWaWRlb0xpbmsoKVwiIGNsYXNzPVwiYnV0dG9uLXZpZGVvXCIgdHlwZT1cImJ1dHRvblwiPkluZm9ybWF0aXZlIFZpZGVvPC9idXR0b24+XG4gIDxidXR0b24gKGNsaWNrKT1cIk9uQ2xpY2tJbmZvTGluaygpXCIgY2xhc3M9XCJidXR0b24taW5mb3JtYXRpb25cIiB0eXBlPVwiYnV0dG9uXCI+T3RoZXIgSW5mb3JtYXRpb248L2J1dHRvbj5cblxuPC9odG1sPlxuIiwiPHRoYW5rLXlvdT48L3RoYW5rLXlvdT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQWUsMENBQ2Y7TUFBQTtNQUFBLDRDQUFNO01BQUEsU0FDTjtNQUFBLHdFQUFNO2FBQUEsMkJBQ0M7TUFDTDtVQUFBO2FBQUE7TUFBYSw4Q0FFYjtVQUFBO1VBQUEsOEJBQUk7TUFBZ0IsNENBQ3BCO1VBQUE7VUFBQTtZQUFBO1lBQUE7WUFBUTtjQUFBO2NBQUE7WUFBQTtZQUFSO1VBQUEsZ0NBQXdFO01BQTBCLDRDQUNsRztVQUFBO1VBQUE7WUFBQTtZQUFBO1lBQVE7Y0FBQTtjQUFBO1lBQUE7WUFBUjtVQUFBLGdDQUE2RTtNQUEwQiw0Q0FFbEc7VUFBQTs7SUFKRDtJQUFBOzs7O29CQ05OO01BQUE7a0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
