/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h2[_ngcontent-%COMP%]{top:50%;left:50%;width:500px;height:50px;margin-left:-200px;margin-top:-25px}.button-video[_ngcontent-%COMP%], h2[_ngcontent-%COMP%]{position:absolute;font-family:Roboto,sans-serif;font-size:30px;color:#fff}.button-video[_ngcontent-%COMP%]{top:55%;left:20%;width:60%;height:80px;background-color:#004273;border:2px solid #93b9dd;border-radius:4px}.button-information[_ngcontent-%COMP%]:hover, .button-video[_ngcontent-%COMP%]:hover{background-color:#005690;cursor:pointer}.button-information[_ngcontent-%COMP%]{position:absolute;top:70%;left:20%;height:80px;width:60%;background-color:#004273;font-family:Roboto,sans-serif;font-size:30px;color:#fff;border:2px solid#93b9dd;border-radius:4px}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90aGFuay15b3UvdGhhbmsteW91LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL3RoYW5rLXlvdS90aGFuay15b3UuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
