/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.container[_ngcontent-%COMP%]{width:100%;height:100%}.parent-container[_ngcontent-%COMP%]{width:100%;height:35%}.child-container[_ngcontent-%COMP%]{width:100%}[_nghost-%COMP%]     .logo{margin-top:2%;width:80%}button[_ngcontent-%COMP%]{height:60%;background-color:#004273;font-family:Roboto;font-size:2em;color:#fff;border:2px solid #93b9dd;border-radius:8px;margin-bottom:20%;padding:4%}@media (orientation:landscape){button[_ngcontent-%COMP%]{height:85%}}@media (max-width:610px){button[_ngcontent-%COMP%]{font-size:.9em;height:80%}}@media (orientation:landscape) and (max-width:650px){button[_ngcontent-%COMP%]{font-size:.95em}}@media (max-height:600px) and (min-height:410px){button[_ngcontent-%COMP%]{font-size:.95em;margin-bottom:5%}.child-container[_ngcontent-%COMP%]{width:70%;margin-left:15%}}@media (min-height:1350px) and (min-width:1024px){button[_ngcontent-%COMP%]{font-size:2em}}@media (max-height:400px){button[_ngcontent-%COMP%]{font-size:.7em;margin-bottom:5%}.child-container[_ngcontent-%COMP%]{width:70%;margin-left:15%}}button[_ngcontent-%COMP%]:hover{background-color:#005690;cursor:pointer}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9ob21lL2hvbWUuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
