/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/no-content/no-content.component';
const styles_NoContentComponent:any[] = ([] as any[]);
export const RenderType_NoContentComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NoContentComponent,data:{}});
export function View_NoContentComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n      '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['404: page missing'])),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    '])),(_l()(),i0.ɵted(-1,(null as any),['\n  ']))],(null as any),(null as any));
}
export function View_NoContentComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'no-content',
      ([] as any[]),(null as any),(null as any),(null as any),View_NoContentComponent_0,
      RenderType_NoContentComponent)),i0.ɵdid(1,49152,(null as any),0,i1.NoContentComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NoContentComponentNgFactory:i0.ComponentFactory<i1.NoContentComponent> = i0.ɵccf('no-content',
    i1.NoContentComponent,View_NoContentComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9uby1jb250ZW50L25vLWNvbnRlbnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9uby1jb250ZW50L25vLWNvbnRlbnQuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL25vLWNvbnRlbnQvbm8tY29udGVudC5jb21wb25lbnQudHMuTm9Db250ZW50Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvbm8tY29udGVudC9uby1jb250ZW50LmNvbXBvbmVudC50cy5Ob0NvbnRlbnRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2PlxuICAgICAgPGgxPjQwNDogcGFnZSBtaXNzaW5nPC9oMT5cbiAgICA8L2Rpdj5cbiAgIiwiPG5vLWNvbnRlbnQ+PC9uby1jb250ZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDhDQUNJO01BQUE7TUFBQSw0Q0FBSztNQUFBLGVBQ0g7TUFBQSx3RUFBSTthQUFBLDBDQUFzQjtNQUFBLGFBQ3RCOzs7b0JDSFY7TUFBQTttQ0FBQSxVQUFBO01BQUE7OzsifQ==
