/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/audiologist-navigation/audiologist-navigation.component';
import * as i1 from './audiologist-navigation.component.ngfactory';
export function AudiologistNavigationComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AudiologistNavigationComponent,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},isComponent:true,selector:'audio-navigation',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i1.View_AudiologistNavigationComponent_0,
      rendererType:i1.RenderType_AudiologistNavigationComponent,componentFactory:i1.AudiologistNavigationComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9hdWRpb2xvZ2lzdC1uYXZpZ2F0aW9uL2F1ZGlvbG9naXN0LW5hdmlnYXRpb24uY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9hdWRpb2xvZ2lzdC1uYXZpZ2F0aW9uL2F1ZGlvbG9naXN0LW5hdmlnYXRpb24uY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
