/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/appointments/appointments.component';
import * as i1 from './appointments.component.ngfactory';
export function AppointmentsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AppointmentsComponent,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},isComponent:true,selector:'appointments',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i1.View_AppointmentsComponent_0,rendererType:i1.RenderType_AppointmentsComponent,
      componentFactory:i1.AppointmentsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9hcHBvaW50bWVudHMvYXBwb2ludG1lbnRzLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvYXBwb2ludG1lbnRzL2FwcG9pbnRtZW50cy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
