/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './tfi.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/tfi/tfi.component';
const styles_TfiComponent:any[] = [i0.styles];
export const RenderType_TfiComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_TfiComponent,
    data:{}});
export function View_TfiComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  tfi works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_TfiComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-tfi',([] as any[]),
      (null as any),(null as any),(null as any),View_TfiComponent_0,RenderType_TfiComponent)),
      i1.ɵdid(1,114688,(null as any),0,i2.TfiComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TfiComponentNgFactory:i1.ComponentFactory<i2.TfiComponent> = i1.ɵccf('app-tfi',
    i2.TfiComponent,View_TfiComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90ZmkvdGZpLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvdGZpL3RmaS5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvdGZpL3RmaS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90ZmkvdGZpLmNvbXBvbmVudC50cy5UZmlDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgdGZpIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC10Zmk+PC9hcHAtdGZpPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEseUNBRUM7TUFBQTs7O29CQ0ZKO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
