/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './summary.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/summary/summary.component';
const styles_SummaryComponent:any[] = [i0.styles];
export const RenderType_SummaryComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SummaryComponent,data:{}});
export function View_SummaryComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  summary works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_SummaryComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-summary',
      ([] as any[]),(null as any),(null as any),(null as any),View_SummaryComponent_0,
      RenderType_SummaryComponent)),i1.ɵdid(1,114688,(null as any),0,i2.SummaryComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SummaryComponentNgFactory:i1.ComponentFactory<i2.SummaryComponent> = i1.ɵccf('app-summary',
    i2.SummaryComponent,View_SummaryComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9zdW1tYXJ5L3N1bW1hcnkuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9zdW1tYXJ5L3N1bW1hcnkuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL3N1bW1hcnkvc3VtbWFyeS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9zdW1tYXJ5L3N1bW1hcnkuY29tcG9uZW50LnRzLlN1bW1hcnlDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgc3VtbWFyeSB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtc3VtbWFyeT48L2FwcC1zdW1tYXJ5PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsNkNBRUM7TUFBQTs7O29CQ0ZKO01BQUE7aUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
