/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './logo.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/logo/logo.component';
import * as i3 from '@angular/router';
const styles_LogoComponent:any[] = [i0.styles];
export const RenderType_LogoComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_LogoComponent,data:{}});
export function View_LogoComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n      '])),(_l()(),i1.ɵeld(1,
      0,(null as any),(null as any),3,'div',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['\n        '])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),0,'img',[['alt',
      'Logo'],['class','logo']],[[8,'src',4]],[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:i2.LogoComponent = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.onClick()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n      '])),
      (_l()(),i1.ɵted(-1,(null as any),['\n  ']))],(null as any),(_ck,_v) => {
    var _co:i2.LogoComponent = _v.component;
    const currVal_0:any = _co.imgLink;
    _ck(_v,3,0,currVal_0);
  });
}
export function View_LogoComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'logo',([] as any[]),
      (null as any),(null as any),(null as any),View_LogoComponent_0,RenderType_LogoComponent)),
      i1.ɵdid(1,49152,(null as any),0,i2.LogoComponent,[i3.Router],(null as any),(null as any))],
      (null as any),(null as any));
}
export const LogoComponentNgFactory:i1.ComponentFactory<i2.LogoComponent> = i1.ɵccf('logo',
    i2.LogoComponent,View_LogoComponent_Host_0,{logoRouteOption:'logoRouteOption',
        imgLink:'imgLink'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9sb2dvL2xvZ28uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9sb2dvL2xvZ28uY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL2xvZ28vbG9nby5jb21wb25lbnQudHMuTG9nb0NvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL2xvZ28vbG9nby5jb21wb25lbnQudHMuTG9nb0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgPGRpdj5cbiAgICAgICAgPGltZyAgKGNsaWNrKT1cIm9uQ2xpY2soKVwiIGNsYXNzPVwibG9nb1wiIFtzcmNdPVwiaW1nTGlua1wiIGFsdD1cIkxvZ29cIi8+XG4gICAgICA8L2Rpdj5cbiAgIiwiPGxvZ28+PC9sb2dvPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsZ0RBQ007TUFBQTtNQUFBLDRDQUFLO01BQUEsaUJBQ0g7TUFBQTtJQUFBO0lBQUE7SUFBTTtNQUFBO01BQUE7SUFBQTtJQUFOO0VBQUEsZ0NBQW1FO01BQy9EOztJQURtQztJQUF2QyxXQUF1QyxTQUF2Qzs7OztvQkNGUjtNQUFBO2FBQUE7Ozs7OyJ9
