/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['img.logo[_ngcontent-%COMP%]{padding-top:25px}@media (max-height:400px){.logo[_ngcontent-%COMP%]{margin-top:2%;width:60%;margin-left:0}}@media (max-height:600px) and (min-height:410px){.logo[_ngcontent-%COMP%]{margin-top:2%;width:60%;margin-left:0}}img.logo[_ngcontent-%COMP%]:hover{opacity:.5;cursor:pointer;border:none}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9sb2dvL2xvZ28uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90dXR1eWluL1ZBLUF1ZGlvbG9neS1XZWJzaXRlL3NyYy9hcHAvbG9nby9sb2dvLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
