/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './custom-resource-strings.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/common/custom-resource-strings.component';
const styles_CustomResourceStringsComponent:any[] = [i0.styles];
export const RenderType_CustomResourceStringsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_CustomResourceStringsComponent,data:{}});
export function View_CustomResourceStringsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  custom-resource-strings works!\n'])),(_l()(),
      i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_CustomResourceStringsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-custom-resource-strings',
      ([] as any[]),(null as any),(null as any),(null as any),View_CustomResourceStringsComponent_0,
      RenderType_CustomResourceStringsComponent)),i1.ɵdid(1,49152,(null as any),0,
      i2.CustomResourceStringsComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const CustomResourceStringsComponentNgFactory:i1.ComponentFactory<i2.CustomResourceStringsComponent> = i1.ɵccf('app-custom-resource-strings',
    i2.CustomResourceStringsComponent,View_CustomResourceStringsComponent_Host_0,{},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9jb21tb24vY3VzdG9tLXJlc291cmNlLXN0cmluZ3MuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9jb21tb24vY3VzdG9tLXJlc291cmNlLXN0cmluZ3MuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL2NvbW1vbi9jdXN0b20tcmVzb3VyY2Utc3RyaW5ncy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC9jb21tb24vY3VzdG9tLXJlc291cmNlLXN0cmluZ3MuY29tcG9uZW50LnRzLkN1c3RvbVJlc291cmNlU3RyaW5nc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBjdXN0b20tcmVzb3VyY2Utc3RyaW5ncyB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtY3VzdG9tLXJlc291cmNlLXN0cmluZ3M+PC9hcHAtY3VzdG9tLXJlc291cmNlLXN0cmluZ3M+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSw2REFFQzthQUFBOzs7b0JDRko7TUFBQTsrQ0FBQSxVQUFBO3dDQUFBOzs7OzsifQ==
