/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ts-screener-question.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../src/app/ts-screener/ts-screener-question/ts-screener-question.component';
const styles_TsScreenerQuestionComponent:any[] = [i0.styles];
export const RenderType_TsScreenerQuestionComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_TsScreenerQuestionComponent,data:{}});
export function View_TsScreenerQuestionComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  ts-screener-question works!\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n']))],(null as any),(null as any));
}
export function View_TsScreenerQuestionComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-ts-screener-question',
      ([] as any[]),(null as any),(null as any),(null as any),View_TsScreenerQuestionComponent_0,
      RenderType_TsScreenerQuestionComponent)),i1.ɵdid(1,114688,(null as any),0,i2.TsScreenerQuestionComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TsScreenerQuestionComponentNgFactory:i1.ComponentFactory<i2.TsScreenerQuestionComponent> = i1.ɵccf('app-ts-screener-question',
    i2.TsScreenerQuestionComponent,View_TsScreenerQuestionComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90cy1zY3JlZW5lci90cy1zY3JlZW5lci1xdWVzdGlvbi90cy1zY3JlZW5lci1xdWVzdGlvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL3RzLXNjcmVlbmVyL3RzLXNjcmVlbmVyLXF1ZXN0aW9uL3RzLXNjcmVlbmVyLXF1ZXN0aW9uLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90cy1zY3JlZW5lci90cy1zY3JlZW5lci1xdWVzdGlvbi90cy1zY3JlZW5lci1xdWVzdGlvbi5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90cy1zY3JlZW5lci90cy1zY3JlZW5lci1xdWVzdGlvbi90cy1zY3JlZW5lci1xdWVzdGlvbi5jb21wb25lbnQudHMuVHNTY3JlZW5lclF1ZXN0aW9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHRzLXNjcmVlbmVyLXF1ZXN0aW9uIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC10cy1zY3JlZW5lci1xdWVzdGlvbj48L2FwcC10cy1zY3JlZW5lci1xdWVzdGlvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDBEQUVDO01BQUE7OztvQkNGSjtNQUFBOzRDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
