/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ts-screener.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/ts-screener/ts-screener.component';
const styles_TsScreenerComponent:any[] = [i0.styles];
export const RenderType_TsScreenerComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_TsScreenerComponent,data:{}});
export function View_TsScreenerComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  ts-screener works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_TsScreenerComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-ts-screener',
      ([] as any[]),(null as any),(null as any),(null as any),View_TsScreenerComponent_0,
      RenderType_TsScreenerComponent)),i1.ɵdid(1,114688,(null as any),0,i2.TsScreenerComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TsScreenerComponentNgFactory:i1.ComponentFactory<i2.TsScreenerComponent> = i1.ɵccf('app-ts-screener',
    i2.TsScreenerComponent,View_TsScreenerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90cy1zY3JlZW5lci90cy1zY3JlZW5lci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdHV0dXlpbi9WQS1BdWRpb2xvZ3ktV2Vic2l0ZS9zcmMvYXBwL3RzLXNjcmVlbmVyL3RzLXNjcmVlbmVyLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90cy1zY3JlZW5lci90cy1zY3JlZW5lci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1dHV5aW4vVkEtQXVkaW9sb2d5LVdlYnNpdGUvc3JjL2FwcC90cy1zY3JlZW5lci90cy1zY3JlZW5lci5jb21wb25lbnQudHMuVHNTY3JlZW5lckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICB0cy1zY3JlZW5lciB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtdHMtc2NyZWVuZXI+PC9hcHAtdHMtc2NyZWVuZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSxpREFFQztNQUFBOzs7b0JDRko7TUFBQTtvQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
